name: "Docker build and push"
description: "Reusable action for login to docker hub"
inputs:
  dockerhub_username:
    description: "Docker hub username"
    required: true
    
  dockerhub_password:
    description: "Docker hub password"
    required: true
  
runs:
  using: "composite"
  steps:
  - name: "Login to Docker Hub"
    uses: docker/login-action@v3
    with:
      username: ${{inputs.dockerhub_username}}
      password: ${{inputs.dockerhub_password}}